const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS

  HOME_SCREEN: 'HOME',
  PROFILE_SCREEN: 'STUDENTS',
  NOTIFICATION_SCREEN: 'NOTIFICATIONS',

  CHARGE_DETAIL_SCREEN: 'CHARGE_DETAIL_SCREEN',
  NOC_MOVE_IN_SCREEN: 'NOC_MOVE_IN_SCREEN',
  NOC_MOVE_IN_DASHBOARD_SCREEN: 'NOC_MOVE_IN_DASHBOARD_SCREEN',
  NOC_MOVE_OUT_SCREEN: 'NOC_MOVE_OUT_SCREEN',
  NOC_MOVE_OUT_DASHBOARD_SCREEN: 'NOC_MOVE_OUT_DASHBOARD_SCREEN',
  MESSAGES_SCREEN: 'MESSAGES_SCREEN',
  MESSAGES_DETAIL_SCREEN: 'MESSAGES_DETAIL_SCREEN',
  NOC_MAINTENANCE_DASHBOARD_SCREEN: 'NOC_MAINTENANCE_DASHBOARD_SCREEN',
  NOC_MAINTENANCE_SCREEN: 'NOC_MAINTENANCE_SCREEN',
  REPORT_ISSUES_SCREEN: 'REPORT_ISSUES_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN'
};

export default Routes;
