const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS
  ASSOCIATION_HOME_STACK: 'ASSOCIATION_HOME_STACK',

  ASSOCIATION_REQUEST_SCREEN: 'ASSOCIATION_REQUEST_SCREEN',
  ASSOCIATION_REQUEST_DETAIL: 'ASSOCIATION_REQUEST_DETAIL',
  ASSOCIATION_ANNOUNCE_SCREEN: 'ASSOCIATION_ANNOUNCE_SCREEN',
  ASSOCIATION_ANNOUNCE_DETAIL_SCREEN: 'ASSOCIATION_ANNOUNCE_DETAIL_SCREEN',
  ASSOCIATION_ANNOUNCE_SEND_OFFER: 'ASSOCIATION_ANNOUNCE_SEND_OFFER',
  ASSOCIATION_SENDOUT_DETAIL_SCREEN: 'ASSOCIATION_SENDOUT_DETAIL_SCREEN',
  ASSOCIATION_SENDOUT_SCREEN: 'ASSOCIATION_SENDOUT_SCREEN',
  ASSOCIATION_SETTINGS_SCREEN: 'ASSOCIATION_SETTINGS_SCREEN',
  ASSOCIATION_ADD_BUILDINGS: 'ASSOCIATION_ADD_BUILDINGS',
  ASSOCIATION_OWNER_DETAIL: 'ASSOCIATION_OWNER_DETAIL',
  ASSOCIATION_MANAGE_OWNERS: 'ASSOCIATION_MANAGE_OWNERS',
  ASSOCIATION_REPORT_SCREEN: 'ASSOCIATION_REPORT_SCREEN',
  ASSOCIATION_SEARCH_SCREEN: 'ASSOCIATION_SEARCH_SCREEN',
  
  HOME_SCREEN: 'HOME',
  PROFILE_SCREEN: 'STUDENTS',
  NOTIFICATION_SCREEN: 'NOTIFICATIONS',

  CHARGE_DETAIL_SCREEN: 'CHARGE_DETAIL_SCREEN',
  NOC_MOVE_IN_SCREEN: 'NOC_MOVE_IN_SCREEN',
  NOC_MOVE_IN_DASHBOARD_SCREEN: 'NOC_MOVE_IN_DASHBOARD_SCREEN',
  NOC_MOVE_OUT_SCREEN: 'NOC_MOVE_OUT_SCREEN',
  NOC_MOVE_OUT_DASHBOARD_SCREEN: 'NOC_MOVE_OUT_DASHBOARD_SCREEN',
  MESSAGES_SCREEN: 'MESSAGES_SCREEN',
  MESSAGES_DETAIL_SCREEN: 'MESSAGES_DETAIL_SCREEN',
  NOC_MAINTENANCE_DASHBOARD_SCREEN: 'NOC_MAINTENANCE_DASHBOARD_SCREEN',
  NOC_MAINTENANCE_SCREEN: 'NOC_MAINTENANCE_SCREEN',
  REPORT_ISSUES_SCREEN: 'REPORT_ISSUES_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN'
};

export default Routes;
